language: python
python:
    - '3.6'

services:
    - postgresql

# Install dependencies
install:
    - pip install -r requirements.txt
    - pip install -r requirements_mysql.txt

# Prepare the working environment
before_script:
    - cp buk/local_settings_example.py buk/local_settings.py
    - psql -c 'create database buk;' -U postgres

# Run tests
script:
    - python manage.py makemigrations --check
    - python manage.py test
