language: python
python:
    - '3.6'

addons:
    postgresql: 9.6

# Install dependencies
install:
    - pip install pipenv
    - pipenv install --dev --deploy

# Prepare the working environment
before_script:
    - psql --version
    - psql -c 'create database buk;' -U postgres

# Run tests
script:
    - cp buk/local_settings_example_psql.py buk/local_settings.py
    - coverage run --source='.' manage.py test
    - cp buk/local_settings_example_sqlite.py buk/local_settings.py
    - ./manage.py test

after_success:
    - codecov
