# Generated by Django 2.0.2 on 2018-04-10 15:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='tittel')),
                ('visibility', models.CharField(choices=[('PUB', 'Offentlig'), ('INT', 'Intern'), ('ADM', 'Admin')], max_length=3, verbose_name='synlighet')),
                ('location', models.CharField(max_length=150, verbose_name='sted')),
            ],
            options={
                'verbose_name': 'aktivitet',
                'verbose_name_plural': 'aktiviteter',
            },
        ),
        migrations.CreateModel(
            name='ActivityPeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateField(verbose_name='start')),
                ('end', models.DateField(blank=True, null=True, verbose_name='slutt')),
            ],
            options={
                'verbose_name': 'periode',
                'verbose_name_plural': 'perioder',
                'ordering': ['end', 'start'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Concert',
            fields=[
                ('activity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='activities.Activity')),
            ],
            options={
                'verbose_name': 'konsert',
                'verbose_name_plural': 'konserter',
            },
            bases=('activities.activity',),
        ),
        migrations.CreateModel(
            name='Other',
            fields=[
                ('activity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='activities.Activity')),
            ],
            options={
                'verbose_name': 'Annet',
                'verbose_name_plural': 'Annet',
            },
            bases=('activities.activity',),
        ),
        migrations.CreateModel(
            name='Rehearsal',
            fields=[
                ('activity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='activities.Activity')),
            ],
            options={
                'verbose_name': 'øvelse',
                'verbose_name_plural': 'øvelser',
            },
            bases=('activities.activity',),
        ),
        migrations.AddField(
            model_name='activityperiod',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='period', to='activities.Activity'),
        ),
        migrations.AddField(
            model_name='activity',
            name='bakers',
            field=models.ManyToManyField(related_name='baker_for', to=settings.AUTH_USER_MODEL, verbose_name='kakebakere'),
        ),
    ]
