# Generated by Django 2.0.2 on 2018-09-17 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='concert',
            name='price',
            field=models.PositiveIntegerField(default=0, verbose_name='pris vanlig'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='concert',
            name='price_student',
            field=models.PositiveIntegerField(default=0, verbose_name='pris student'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='activityperiod',
            name='end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='slutt'),
        ),
        migrations.AlterField(
            model_name='activityperiod',
            name='start',
            field=models.DateTimeField(verbose_name='start'),
        ),
    ]
