# Generated by Django 2.0.2 on 2018-10-19 20:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_auto_20180917_1117'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='other',
            options={'verbose_name': 'annet', 'verbose_name_plural': 'annet'},
        ),
        migrations.AlterField(
            model_name='activity',
            name='bakers',
            field=models.ManyToManyField(blank=True, related_name='baker_for', to=settings.AUTH_USER_MODEL, verbose_name='kakebakere'),
        ),
    ]
