# Generated by Django 2.0.2 on 2018-11-07 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0004_activity_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='description_internal',
            field=models.TextField(blank=True, help_text='Vises bare for innloggede medlemmer', verbose_name='intern beskrivelse'),
        ),
    ]
