# Generated by Django 2.0.2 on 2018-11-07 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0027_auto_20181019_2216'),
        ('activities', '0005_activity_description_internal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activityperiod',
            options={'ordering': ('-start', 'end')},
        ),
        migrations.AddField(
            model_name='activity',
            name='percussion_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='members.PercussionGroup', verbose_name='slagsverksbæregruppe'),
        ),
        migrations.AlterField(
            model_name='activityperiod',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periods', to='activities.Activity'),
        ),
    ]
