# Generated by Django 2.2.4 on 2019-08-12 14:56

import base.model_fields
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0006_auto_20181107_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='bakers',
            field=base.model_fields.CustomManyToManyField(blank=True, related_name='baker_for', to=settings.AUTH_USER_MODEL, verbose_name='kakebakere'),
        ),
        migrations.AlterField(
            model_name='activityperiod',
            name='end',
            field=base.model_fields.CustomDateTimeField(blank=True, null=True, verbose_name='slutt'),
        ),
        migrations.AlterField(
            model_name='activityperiod',
            name='start',
            field=base.model_fields.CustomDateTimeField(verbose_name='start'),
        ),
    ]
