# Generated by Django 3.0.5 on 2020-04-28 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0007_auto_20190812_1656'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activityperiod',
            options={'ordering': ['end', 'start'], 'verbose_name': 'periode', 'verbose_name_plural': 'perioder'},
        ),
    ]
