# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-02 16:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('last_activity', 'created'), 'permissions': (('view_board_forum', 'Kan se styreforumet'),), 'verbose_name': 'forumpost', 'verbose_name_plural': 'forumposter'},
        ),
        migrations.AddField(
            model_name='post',
            name='forum',
            field=models.CharField(choices=[('MU', 'Musikk og noter'), ('VA', 'Diverse'), ('BO', 'Styret')], default='VA', max_length=2, verbose_name='forum'),
        ),
    ]
