# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-23 17:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_auto_20170702_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='forum',
            field=models.CharField(choices=[('musikk', 'Musikk og noter'), ('diverse', 'Diverse'), ('styret', 'Styret')], default='diverse', max_length=10, verbose_name='forum'),
        ),
    ]
