# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-28 20:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_auto_20170723_1934'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comment',
            new_name='ForumComment',
        ),
        migrations.RenameField(
            model_name='forumcomment',
            old_name='content',
            new_name='comment',
        ),
    ]
