# Generated by Django 2.0.6 on 2018-12-28 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0007_auto_20180207_0030'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-last_activity', '-created'), 'permissions': (('view_board_forum', 'Kan se styreforumet'),), 'verbose_name': 'forumpost', 'verbose_name_plural': 'forumposter'},
        ),
    ]
