# Generated by Django 2.1.1 on 2019-02-07 14:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hat',
            options={'verbose_name': 'hatt', 'verbose_name_plural': 'hatter'},
        ),
        migrations.AlterModelOptions(
            name='instrument',
            options={'verbose_name': 'instrument', 'verbose_name_plural': 'instrumenter'},
        ),
        migrations.AlterModelOptions(
            name='inventoryitem',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='jacket',
            options={'verbose_name': 'jakke', 'verbose_name_plural': 'jakker'},
        ),
        migrations.AlterModelOptions(
            name='pants',
            options={'verbose_name': 'bukse', 'verbose_name_plural': 'bukser'},
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='loaned_to_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loaned_from', to=settings.AUTH_USER_MODEL, verbose_name='loaned_to'),
        ),
    ]
