# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-28 14:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, verbose_name='tittel')),
                ('deadline', models.DateTimeField(blank=True, verbose_name='frist')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PollOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('members', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('poll', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='polls.Poll')),
            ],
        ),
    ]
