# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-28 15:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True, verbose_name='frist'),
        ),
    ]
