# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-29 14:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20170428_1724'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='poll',
            options={'verbose_name': 'påmelding', 'verbose_name_plural': 'påmeldinger'},
        ),
        migrations.AlterModelOptions(
            name='polloption',
            options={'verbose_name': 'valg', 'verbose_name_plural': 'valg'},
        ),
        migrations.RemoveField(
            model_name='poll',
            name='created',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='last_activity',
        ),
    ]
