# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-07 17:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EditableContentImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.EditableContent')),
            ],
        ),
    ]
