# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-07 17:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_editablecontentimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editablecontentimage',
            name='image',
            field=models.ImageField(upload_to='images/editable_content/'),
        ),
    ]
