# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-07 18:36
from __future__ import unicode_literals

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20170407_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editablecontentimage',
            name='image',
            field=models.ImageField(upload_to=base.models.editable_content_image_path),
        ),
    ]
