# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-09 14:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20170407_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editablecontentimage',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='base.EditableContent'),
        ),
    ]
