# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-09 14:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20170409_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editablecontent',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
