# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-25 11:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True, verbose_name='tittel')),
                ('description', models.TextField(blank=True, default='', verbose_name='beskrivelse')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='e-post')),
                ('order', models.IntegerField(default=0, verbose_name='rekkefølge')),
            ],
            options={
                'verbose_name': 'styreverv',
                'verbose_name_plural': 'styreverv',
            },
        ),
        migrations.CreateModel(
            name='Committee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='navn')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='e-post')),
                ('description', models.TextField(blank=True, default='', verbose_name='beskrivelse')),
                ('order', models.IntegerField(default=0, verbose_name='rekkefølge')),
                ('group', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='auth.Group')),
                ('leader_board', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='leaderOf', to='members.BoardPosition', verbose_name='leder i styret')),
            ],
            options={
                'verbose_name': 'komite',
                'verbose_name_plural': 'komiteer',
            },
        ),
        migrations.AddField(
            model_name='instrument',
            name='order',
            field=models.IntegerField(default=0, help_text='Dette angir rekkefølgen instrumentene vises i. Lavere tall kommer først.', verbose_name='rekkefølge'),
        ),
        migrations.AlterField(
            model_name='member',
            name='instrument',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='players', to='members.Instrument', verbose_name='instrument'),
        ),
        migrations.AddField(
            model_name='committee',
            name='leader_member',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='leader_of', to=settings.AUTH_USER_MODEL, verbose_name='leder medlem'),
        ),
        migrations.AddField(
            model_name='committee',
            name='members',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='medlemmer'),
        ),
        migrations.AddField(
            model_name='boardposition',
            name='holder',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='innehaver'),
        ),
        migrations.AlterField(
            model_name='boardposition',
            name='order',
            field=models.IntegerField(default=0, help_text='Dette angir rekkefølgen styrevervene vises i. Lavere tall kommer først.', verbose_name='rekkefølge'),
        ),
        migrations.AlterField(
            model_name='committee',
            name='leader_board',
            field=models.OneToOneField(blank=True, help_text='Lederen for komiteen. Denne eller den under må være satt, men ikke begge.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='leaderOf', to='members.BoardPosition', verbose_name='leder i styret'),
        ),
        migrations.AlterField(
            model_name='committee',
            name='order',
            field=models.IntegerField(default=0, help_text='Dette angir rekkefølgen komiteene vises i. Lavere tall kommer først.', verbose_name='rekkefølge'),
        ),
        migrations.AddField(
            model_name='boardposition',
            name='group',
            field=models.OneToOneField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.Group'),
        ),
        migrations.AlterField(
            model_name='committee',
            name='group',
            field=models.OneToOneField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.Group'),
        ),
        migrations.AlterField(
            model_name='committee',
            name='leader_board',
            field=models.OneToOneField(blank=True, help_text='Lederen for komiteen. Denne eller den under må være satt, men ikke begge.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='leader_of', to='members.BoardPosition', verbose_name='leder i styret'),
        ),
    ]
