# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-09 17:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_auto_20170309_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='committee',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='committees', to=settings.AUTH_USER_MODEL, verbose_name='medlemmer'),
        ),
    ]
