# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-09 18:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_auto_20170309_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='occupation',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='studie/yrke'),
        ),
    ]
