# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-16 12:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0008_auto_20170313_2254'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='membershipperiod',
            options={'ordering': ['end', 'start'], 'verbose_name': 'medlemskapsperiode', 'verbose_name_plural': 'medlemskapsperioder'},
        ),
        migrations.AlterField(
            model_name='membershipperiod',
            name='end',
            field=models.DateField(blank=True, null=True, verbose_name='slutt'),
        ),
    ]
