# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-19 21:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0010_leaveperiod'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ['instrument', '-is_active', 'is_on_leave', 'group_leader_for', 'first_name', 'last_name'], 'verbose_name': 'medlem', 'verbose_name_plural': 'medlemmer'},
        ),
        migrations.AddField(
            model_name='member',
            name='is_on_leave',
            field=models.BooleanField(default=True, verbose_name='i permisjon'),
        ),
    ]
