# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-20 16:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0011_auto_20170319_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardposition',
            name='holder',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='board_position', to=settings.AUTH_USER_MODEL, verbose_name='innehaver'),
        ),
        migrations.AlterField(
            model_name='member',
            name='is_on_leave',
            field=models.BooleanField(default=False, verbose_name='i permisjon'),
        ),
    ]
