# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-21 15:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0012_auto_20170320_1754'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ['instrument', '-is_active', 'is_on_leave', 'group_leader_for', 'first_name', 'last_name'], 'permissions': (('statistics', 'Kan se statistikk for medlemmer'),), 'verbose_name': 'medlem', 'verbose_name_plural': 'medlemmer'},
        ),
    ]
