# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-09 14:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0013_auto_20170321_1607'),
    ]

    operations = [
        migrations.CreateModel(
            name='PercussionCarryingGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='navn')),
                ('leader', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='percussion_group_leader_for', to=settings.AUTH_USER_MODEL, verbose_name='gruppeleder')),
            ],
        ),
        migrations.AddField(
            model_name='member',
            name='percussion_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='members.PercussionCarryingGroup', verbose_name='slagverkgruppe'),
        ),
    ]
