# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-14 16:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0014_auto_20170409_1641'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='percussioncarryinggroup',
            options={'verbose_name': 'slagverkbæregruppe', 'verbose_name_plural': 'slagverkbæregrupper'},
        ),
        migrations.AlterField(
            model_name='percussioncarryinggroup',
            name='name',
            field=models.CharField(editable=False, max_length=50, unique=True, verbose_name='navn'),
        ),
    ]
