# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-15 16:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('members', '0015_auto_20170414_1851'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PercussionCarryingGroup',
            new_name='PercussionGroup',
        ),
    ]
