# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-15 19:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0016_auto_20170415_1847'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='percussiongroup',
            options={'permissions': (('change_percussion_group', 'Kan endre slagverkbæregrupper'),), 'verbose_name': 'slagverkbæregruppe', 'verbose_name_plural': 'slagverkbæregrupper'},
        ),
        migrations.AlterField(
            model_name='percussiongroup',
            name='leader',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='percussion_group_leader_for', to=settings.AUTH_USER_MODEL, verbose_name='gruppeleder'),
        ),
    ]
