# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-19 14:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0017_auto_20170415_2134'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='percussiongroup',
            options={'ordering': ('name',), 'permissions': (('change_percussion_group', 'Kan endre slagverkbæregrupper'),), 'verbose_name': 'slagverkbæregruppe', 'verbose_name_plural': 'slagverkbæregrupper'},
        ),
    ]
