# Generated by Django 2.0.2 on 2018-02-14 22:47

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('members', '0018_auto_20170419_1636'),
    ]

    operations = [
        migrations.CreateModel(
            name='InheritanceGroup',
            fields=[
                ('group_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.Group')),
                ('own_permissions', models.ManyToManyField(blank=True, to='auth.Permission')),
                ('parents', models.ManyToManyField(blank=True, related_name='sub_groups', to='members.InheritanceGroup')),
            ],
            bases=('auth.group',),
            managers=[
                ('objects', django.contrib.auth.models.GroupManager()),
            ],
        ),
        migrations.AddField(
            model_name='boardposition',
            name='inheritance_group',
            field=models.OneToOneField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='members.InheritanceGroup'),
        ),
        migrations.AddField(
            model_name='committee',
            name='inheritance_group',
            field=models.OneToOneField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='members.InheritanceGroup'),
        ),
        migrations.AlterField(
            model_name='committee',
            name='leader_member',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='leader_of', to=settings.AUTH_USER_MODEL, verbose_name='leder medlem'),
        ),
    ]
