# Generated by Django 2.0.2 on 2018-02-14 23:17

from django.db import migrations, IntegrityError


# Django doesn't currently support creating child models from
# existing parent models, so we have a woraround. See this for details:
# https://code.djangoproject.com/ticket/7623#comment:20

def convert_boardposition_group(apps, schema_editor):
    BoardPosition = apps.get_model('members', 'BoardPosition')
    InheritanceGroup = apps.get_model('members', 'Inheritancegroup')

    for pos in BoardPosition.objects.all():
        parent_group = pos.group
        child_group = InheritanceGroup(group_ptr=pos.group)
        child_group.save()
        parent_group.save()

        pos.inheritance_group = InheritanceGroup.objects.get(pk=parent_group.pk)
        pos.save()


def convert_boardposition_group_reverse(apps, schema_editor):
    BoardPosition = apps.get_model('members', 'BoardPosition')
    for pos in BoardPosition.objects.all():
        pos.group = pos.group.group_ptr
        pos.save()


def convert_committee_group(apps, schema_editor):
    Committee = apps.get_model('members', 'Committee')
    InheritanceGroup = apps.get_model('members', 'Inheritancegroup')
    for com in Committee.objects.all():
        parent_group = com.group
        child_group = InheritanceGroup(group_ptr=com.group)
        child_group.save()
        parent_group.save()

        com.inheritance_group = InheritanceGroup.objects.get(pk=parent_group.pk)
        com.save()


def convert_committee_group_reverse(apps, schema_editor):
    Committee = apps.get_model('members', 'Committee')
    for com in Committee.objects.all():
        com.group = com.group.group_ptr
        com.save()


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0019_auto_20180214_2347'),
    ]

    operations = [
        migrations.RunPython(
            convert_boardposition_group,
            reverse_code=convert_boardposition_group_reverse,
        ),
        migrations.RunPython(
            convert_committee_group,
            reverse_code=convert_boardposition_group_reverse,
        ),
    ]
