# Generated by Django 2.0.2 on 2018-02-23 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0020_auto_20180215_0017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boardposition',
            name='group',
        ),
        migrations.RenameField(
            model_name='boardposition',
            old_name='inheritance_group',
            new_name='group',
        ),
        migrations.RemoveField(
            model_name='committee',
            name='group',
        ),
        migrations.RenameField(
            model_name='committee',
            old_name='inheritance_group',
            new_name='group',
        ),
    ]
