# Generated by Django 2.0.2 on 2018-02-23 11:56

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0021_auto_20180223_1357'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='boardposition',
            managers=[
                ('objects', django.contrib.auth.models.GroupManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='committee',
            managers=[
                ('objects', django.contrib.auth.models.GroupManager()),
            ],
        ),
        migrations.AddField(
            model_name='boardposition',
            name='inheritancegroup_ptr',
            field=models.OneToOneField(auto_created=True, null=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, serialize=False, to='members.InheritanceGroup'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='committee',
            name='inheritancegroup_ptr',
            field=models.OneToOneField(auto_created=True, null=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, serialize=False, to='members.InheritanceGroup'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='committee',
            name='leader_member',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='leader_of', to=settings.AUTH_USER_MODEL, verbose_name='leder medlem'),
        ),
        # The primary keys of board positions will change in migration 0023,
        # so we make this field a foreign key temporarily to avoid unique
        # constraint issues
        migrations.AlterField(
            model_name='committee',
            name='leader_board',
            field=models.ForeignKey(blank=True, help_text='Lederen for komiteen. Denne eller den under må være satt, men ikke begge.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='leader_of', to='members.BoardPosition', verbose_name='leder i styret'),
        ),
    ]
