# Generated by Django 2.0.2 on 2018-02-23 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0023_auto_20180223_1256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boardposition',
            name='group',
        ),
        migrations.RemoveField(
            model_name='boardposition',
            name='id',
        ),
        migrations.RemoveField(
            model_name='boardposition',
            name='title',
        ),
        migrations.RemoveField(
            model_name='committee',
            name='group',
        ),
        migrations.RemoveField(
            model_name='committee',
            name='id',
        ),
        migrations.RemoveField(
            model_name='committee',
            name='members',
        ),
        migrations.RemoveField(
            model_name='committee',
            name='name',
        ),
        migrations.AlterField(
            model_name='boardposition',
            name='inheritancegroup_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='members.InheritanceGroup'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='committee',
            name='inheritancegroup_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='members.InheritanceGroup'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='committee',
            name='leader_board',
            field=models.OneToOneField(blank=True, help_text='Lederen for komiteen. Denne eller den under må være satt, men ikke begge.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='leader_of', to='members.BoardPosition', verbose_name='leder i styret'),
        ),
    ]
