# Generated by Django 2.0.2 on 2018-03-02 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0024_auto_20180223_1256'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boardposition',
            options={'ordering': ('order',), 'verbose_name': 'styreverv', 'verbose_name_plural': 'styreverv'},
        ),
        migrations.AlterModelOptions(
            name='committee',
            options={'ordering': ('order',), 'verbose_name': 'komite', 'verbose_name_plural': 'komiteer'},
        ),
    ]
