# Generated by Django 2.0.2 on 2018-10-19 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0026_auto_20180917_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='percussion_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='members.PercussionGroup', verbose_name='slagverkgruppe'),
        ),
    ]
