# Generated by Django 2.0.6 on 2019-01-23 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0026_auto_20181229_0003'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Instrument',
            new_name='InstrumentGroup',
        ),
    ]

    atomic = False
