# Generated by Django 2.1.1 on 2019-02-07 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0027_auto_20190123_1550'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instrumentgroup',
            options={'ordering': ['order', 'name'], 'verbose_name': 'instrumentgruppe', 'verbose_name_plural': 'instrumentgrupper'},
        ),
    ]
