# Generated by Django 2.0.2 on 2018-11-16 13:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0028_auto_20181116_1413'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='committeemembership',
            options={'verbose_name': 'komitemedlem', 'verbose_name_plural': 'komitemedlemmer'},
        ),
        migrations.AlterField(
            model_name='committeemembership',
            name='committee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.Committee', verbose_name='komite'),
        ),
        migrations.AlterField(
            model_name='committeemembership',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='medlem'),
        ),
        migrations.AlterField(
            model_name='committeemembership',
            name='title',
            field=models.CharField(default='Medlem', max_length=100, verbose_name='tittel'),
        ),
    ]
