# Generated by Django 2.1.5 on 2019-01-23 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0029_auto_20181116_1439'),
        ('members', '0026_auto_20181229_0003'),
    ]

    operations = [
    ]
